stages:
  - check

lint:
  stage: check
  image: gradle:8.1.1-jdk17
  script:
    - ./gradlew ktlintCheck
  only:
    - merge_requests

test:
  stage: check
  image: gradle:8.1.1-jdk17
  script:
    - ./gradlew test
  only:
    - merge_requests
