services:
  mysql:
    image: mysql:8.0
    container_name: foodon-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # MySQL root 비밀번호
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # 초기 생성 데이터베이스 이름
      MYSQL_USER: ${MYSQL_USER}                    # 사용자 이름
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # 사용자 비밀번호
      TZ: ${TIMEZONE}                              # 컨테이너의 시간대 설정
    command:
      - --character-set-server=utf8mb4             # 문자 세트
      - --collation-server=utf8mb4_unicode_ci      # 문자 정렬 기준
    volumes:
      - mysql-data:/var/lib/mysql                  # 데이터 영구 저장 위치

  redis:
    image: redis:7.4.2-alpine
    container_name: foodon-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data                           # Redis 데이터 저장

volumes:
  mysql-data:
  redis-data: