spring:
  application:
    name: FoodOn

  config:
    import: optional:file:.env.local[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  auth:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
      refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY}

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
      upload-path: ${S3_UPLOAD_PATH}
      base-url: ${S3_BASE_URL}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
      auto: false
    stack:
      auto: false
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

meal-detect-ai-model:
  url: https://ssafy/api/v1/ai/detect
  
logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
    jdbc:
      sqlonly: DEBUG
      resultsettable: DEBUG
      audit: TRACE
      resultset: TRACE
      connection: OFF
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE


