spring:
  application:
    name: FoodOn

  config:
    import: optional:file:.env.prod[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  auth:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
      refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY}

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
    jdbc:
      sqlonly: DEBUG
      resultsettable: DEBUG
      audit: TRACE
      resultset: TRACE
      connection: OFF
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}