version: '3.8'

services:
  fastapi:
    container_name: fastapi_server
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - shared-model-volume:/shared_model

  airflow-webserver:
    container_name: airflow_webserver
    build:
      context: ./airflow
    restart: always
    depends_on:
      - airflow-scheduler
      - airflow-postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8787
      - AIRFLOW__WEBSERVER__SECRET_KEY=s3cr3t_k3y_4irfl0w_1234567890      
    ports:
      - "8787:8787"
    command: webserver
    volumes:
      - shared-model-volume:/shared_model
      - /home/ubuntu/dataset:/train/dataset  
  airflow-scheduler:
    container_name: airflow_scheduler
    build:
      context: ./airflow
    restart: always
    depends_on:
      - airflow-postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=s3cr3t_k3y_4irfl0w_1234567890
    command: scheduler
    volumes:
      - shared-model-volume:/shared_model
      - /home/ubuntu/dataset:/train/dataset  

  airflow-postgres:
    container_name: airflow_postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  mlflow:
    container_name: mlflow_server
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - /home/ubuntu/mlflow:/mlflow/mlruns
      - shared-model-volume:/shared_model  

volumes:
  postgres-db-volume:
  shared-model-volume:  